# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/image_processing',
                'doc_host': 'https://klausreus.github.io',
                'git_url': 'https://github.com/klausreus/image_processing',
                'lib_path': 'image_processing'},
  'syms': {'image_processing.core': {'image_processing.core.foo': ('core.html#foo', 'image_processing/core.py')}}}
