# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/image_processing',
                'doc_host': 'https://klausreus.github.io',
                'git_url': 'https://github.com/klausreus/image_processing',
                'lib_path': 'image_processing'},
  'syms': { 'image_processing.temperature_extraction': { 'image_processing.temperature_extraction.say_hello': ( 'temperature_extraction.html#say_hello',
                                                                                                                'image_processing/temperature_extraction.py')}}}
